language: python

matrix:
  include:
    - python: '3.5'
      env: TOXENV=py35
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.6'
      env: TOXENV=check
    - python: '3.6'
      env: TOXENV=docs
    - python: '3.7'
      env: TOXENV=py37
      sudo: required
      dist: xenial

install:
  - pip install --upgrade tox codecov pip

script:
  - tox

after_script:
  - codecov
